const message = {
    EMAIL_ALREADY_REGISTERED: 'This email is already been registered',
    REGISTRATION_SUCCESSFUL: 'Registration Successful',
    USER_NOT_REGISTER: 'User not registered',
    INVALID_CREDENTIALS: 'Usermame and Password Invalid',
    USER_LOGIN_SUCCESSFULLY: 'User login successfully',
    CAR_DETAIL_ALREADY_STORED: 'This car details are already been stored',
    CAR_DEATIL_STORED_SUCCESSFULLY: 'Car detail succesfully stored',
    ALL_CAR_GET_SUCCESS: 'All Car Data get Successfully!!',
    CAR_DEL_SUCCESS: 'Car Data deleted Successfully!!',
    REFRESH_TOKEN_NOT_FOUND: 'Refresh token not found',
    TOKEN_GENERATED_SUCCESSFULY: 'Token Generated Successfuy',
    PLEASE_SELECT_IMAGE: 'Please select image',
    PLEASE_SELECT_PRIMARY_CAR_IMAGE: 'Please select primary car image',
    RIDE_ADD_SUCCESS: 'Ride Add Successfull',
    RIDE_ALREDY_ADDED: 'Ride alredy added',
    RIDE_AD_RETRIEVED_SUCCESS: 'Ride add retrived success',
    REQUEST_ALREADY_EXIST: 'You Already Request for this!',
    USER_REQUEST_SUBMITED_SUCCESSFULLY: 'User request submited Successfully!',
    ALL_REQ_GET_SUCCESS: 'All Request for your ride is get Successfully!!',
    UPDATE_REQUEST: 'Ride Request Updated Successfully!',
    SAVE_RATING: 'Your Rating Submited Successfully!',
    RIDER_ADD_DOEST_NOT_EXIST:'Rider add does not exist',
    INVALID_NUMBER_ENTERED: 'Invalid number entered',
    CAR_IMAGE_DELETED_SUCCESSFULLY: 'Car image deleted successfully',
    CAR_DEATIL_UPDATED_SUCCESSFULLY: 'Car detail updated successfully',
    STATUS_FIELD_IS_REQUIRED: 'Status field is required',
    USER_ID_FIELD_IS_REQUIRED: 'User Id field is required',
    USER_STATUS_UPDATED_SUCCESFULLY: 'User status updated successfully',
    CAR_NOT_FOUD: 'Car not found',
    NUMBER_AND_TOAL_SEAT_REQUIRED:'number and total seat required',
    USER_PROFILE_UPDATE_SUCCESSFULLY: 'User profile update successfully',
    USER_REQUEST_NOT_EXISTS_OR_PENDING:'User request not exists or pending!',
    RIDE_REQUEST_ALREADY_EXISTS: 'Ride request already exists',
    NO_RIDE_REQUEST_FOUND: 'No ride request found',
    RIDE_REQUEST_RETRIVED_SUCCESS: 'Ride Request retrived success',
    RIDE_REQUEST_NOT_EXISTS: 'Ride request not exists',
    USER_RIDE_REQUEST_UPDATED_SUCCESSFULLY:'User ride request updated successfully',
    NO_RIDES_FOUND: 'No rides found!',
    USER_NOT_FOUND: 'User not found!',
    RIDE_RETRIEVED_SUCCESS:'Ride retrieved success',
    USER_RIDE_REQUEST_DELETED_SUCCESSFULLY: 'User ride request deleted successfully',
    PENDING_APPROVAL: 'Please wait until admin approves your registration',
    REJECTED_REGISTRATION: 'Your registration is rejected by admin due to unexpected behaviours. Please contact administrator to recover your account',
    RIDE_DELETE_SUCCESS: 'Ride successfully deleted',
};

const getMessage = (key)=>{
    if(message[key]) return message[key];
    return 'Message key not found';
}

module.exports = getMessage;